### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()" because "itemMeta" is null

### ISSUE THREAD

**Issue by AGuyNamedJens** [xKaYoz/AkarianAuctionHouse#15]
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()" because "itemMeta" is null

I don't even get what's wrong now..

**Comment by xKaYoz** [comment]
Hey there!

What did you or a player do that caused the error? And can you send me the entire error message so I can read what is happening.

**Comment by AGuyNamedJens** [comment]
I did nothing, i just opened with /ah and it just broke.. restart fixed it but probably not for long..

**Comment by xKaYoz** [comment]
The issue that it had was how it handles the IDs for the auctions to tell which ones are which. Would you mind sending me the full error message so I can read where the error is located

**Comment by AGuyNamedJens** [comment]
Still weird though.. Never touched anything, only let a bedrock player open /ah and then it just broke..

```[19:42:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ah' in plugin AuctionHouse v1.2.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2371) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2331) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by xKaYoz** [comment]
When opening the Auction house is when the PersistentContainers are used. Was there any more to the error message after that? This snippet does not show where the error produced in my code.

Thanks!

**Comment by AGuyNamedJens** [comment]
oh yeah right, forgot the other lines

```[19:42:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ah' in plugin AuctionHouse v1.2.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2371) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2331) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.19.4.jar:git-Purpur-1942]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()" because "itemMeta" is null
	at net.akarian.auctionhouse.listings.Listing.createActiveListing(Listing.java:279) ~[AuctionHouse (3).jar:?]
	at net.akarian.auctionhouse.guis.AuctionHouseGUI.updateInventory(AuctionHouseGUI.java:412) ~[AuctionHouse (3).jar:?]
	at net.akarian.auctionhouse.guis.AuctionHouseGUI.getInventory(AuctionHouseGUI.java:215) ~[AuctionHouse (3).jar:?]
	at net.akarian.auctionhouse.commands.main.AuctionHouseCommand.onCommand(AuctionHouseCommand.java:36) ~[AuctionHouse (3).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 23 more```

**Comment by xKaYoz** [comment]
When this happened did it only break for the user or did it break for everyone? Did they try to do the command again and if so, did it do the error again?

Thanks!

**Comment by AGuyNamedJens** [comment]
happends to everyone, auction house literally stops functioning until i forcefully restart the server, even a reload doesn't work

**Comment by AGuyNamedJens** [comment]
another issue besides for this one arised (this one however seems to have been resolved after a reboot)
```[17:57:32 WARN]: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect DECIMAL value: '00000000-0000-0000-0009-01f56dc607d0'
[17:57:32 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[17:57:32 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[17:57:32 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
[17:57:32 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
[17:57:32 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
[17:57:32 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
[17:57:32 WARN]:        at AuctionHouse (1).jar//net.akarian.auctionhouse.users.UserSettings.lambda$save$1(UserSettings.java:162)
[17:57:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:57:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:57:32 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:57:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:57:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:57:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by xKaYoz** [comment]
Closing issue due to fixes being implemented. Created checks that pre-encodes the item to avoid the loading issue presented here. Also implemented a fix that will remove broken auctions and reports to admins.
