### ISSUE TITLE
[BUG] Sudden errors on initialisation (getListingManager returns null)

### ISSUE THREAD

**Issue by Jameskmonger** [xKaYoz/AkarianAuctionHouse#30]
**Describe the bug**
- as of yesterday there appears to be an issue which is preventing AuctionHouse from loading.
- I haven't updated any plugins nor server versions

**To Reproduce**
I don't have any real steps to reproduce this, it happens on every startup. Nothing has changed in my server configuration.

**Expected behavior**
The plugin should load successfully.

**Server Type and Version:**
- PurpurMC 1.20.1 build 2020, also build 2033 and 2036

**Additional context**
```
[12:13:37 INFO]: [AuctionHouse] Enabling AuctionHouse v1.3.0_Pre-4
[12:13:37 INFO]: [AuctionHouse] ========== Akarian Auction House ==========
[12:13:37 INFO]: [AuctionHouse]  
[12:13:37 INFO]: [AuctionHouse] Loading Akarian Auction House v1.3.0_Pre-4...
[12:13:37 INFO]: [AuctionHouse] Setting up Economy...
[12:13:37 INFO]: [AuctionHouse] Successfully hooked into EssentialsX Economy.
[12:13:37 INFO]: [AuctionHouse] Loading database...
[12:13:37 INFO]: [AuctionHouse] Successfully connected to FILE database.
[12:13:37 INFO]: [AuctionHouse] Loading listings...
[12:13:37 ERROR]: Error occurred while enabling AuctionHouse v1.3.0_Pre-4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.akarian.auctionhouse.listings.ListingManager.getActive()" because the return value of "net.akarian.auctionhouse.AuctionHouse.getListingManager()" is null
        at net.akarian.auctionhouse.listings.Listing.setExpired(Listing.java:357) ~[AuctionHouse.jar:?]
        at net.akarian.auctionhouse.listings.ListingManager.expire(ListingManager.java:889) ~[AuctionHouse.jar:?]
        at net.akarian.auctionhouse.listings.ListingManager.loadListings(ListingManager.java:992) ~[AuctionHouse.jar:?]
        at net.akarian.auctionhouse.listings.ListingManager.<init>(ListingManager.java:59) ~[AuctionHouse.jar:?]
        at net.akarian.auctionhouse.AuctionHouse.onEnable(AuctionHouse.java:156) ~[AuctionHouse.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:13:37 INFO]: [AuctionHouse] Disabling AuctionHouse v1.3.0_Pre-4
[12:13:37 INFO]: [AuctionHouse] Zipped log 2023-08-21-002.
[12:13:37 INFO]: [AuctionHouse] =================================================
```

and here is the `AuctionHouse/logs/` file

```
[2023/08/21 12:13:37] ChatManager Successfully Loaded
[2023/08/21 12:13:37] Checking for Floodgate...
[2023/08/21 12:13:37] Floodgate found and enabled
[2023/08/21 12:13:37] Loading NameManager...
[2023/08/21 12:13:37] NameManager Successfully Loaded
[2023/08/21 12:13:37] Loading Messages...
[2023/08/21 12:13:37] Messages Successfully Loaded
[2023/08/21 12:13:37] Loading MySQL...
[2023/08/21 12:13:37] MySQL Successfully Loaded
[2023/08/21 12:13:37] Loading UpdateManager...
[2023/08/21 12:13:37] UpdateManager Successfully Loaded
[2023/08/21 12:13:37] Loading GUIManager...
[2023/08/21 12:13:37] GUIManager Successfully Loaded
[2023/08/21 12:13:37] Loading CooldownManager...
[2023/08/21 12:13:37] Loaded 0 cooldowns.
[2023/08/21 12:13:37] Loading listings...
```

**Comment by Jameskmonger** [comment]
I notice that the code in `ListingManager` doesn't match up to the stack trace, too (as far as I can tell..)

The stack trace shows `ListingManager.loadListings` being called by `ListingManager.<init>` - but the constructor of `ListingManager` on GitHub does not call `loadListings` (instead it's called by `startup`)

**Comment by xKaYoz** [comment]
> I notice that the code in `ListingManager` doesn't match up to the stack trace, too (as far as I can tell..)
> 
> The stack trace shows `ListingManager.loadListings` being called by `ListingManager.<init>` - but the constructor of `ListingManager` on GitHub does not call `loadListings` (instead it's called by `startup`)

Hello there! 

This is because I have fixed it and pushed the commit. I have a build of this posted in the general chat in the discord server.

Thanks again and sorry for the issues!
